# Generated by Django 4.2.3 on 2023-08-03 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulcastService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmtp_url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=80, null=True)),
                ('stream_key', models.CharField(max_length=64, null=True)),
                ('playback_id', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('disabled', 'Disabled')], default='idle', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7)),
                ('latency_mode', models.CharField(choices=[('low', 'Low'), ('reduced', 'Reduced'), ('standard', 'Standard')], default='standard', max_length=8)),
                ('test_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='live.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StreamThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(default='lives/thumbnails/default.png', upload_to='lives\\thumbnails/')),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='live.stream')),
            ],
        ),
        migrations.CreateModel(
            name='StreamStatusJWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_jwt', to='live.stream')),
            ],
        ),
        migrations.CreateModel(
            name='Simulcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulcast_id', models.CharField(max_length=128, unique=True)),
                ('stream_key', models.CharField(max_length=128, unique=True)),
                ('url', models.CharField(max_length=512)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.stream')),
            ],
            options={
                'unique_together': {('stream_key', 'stream')},
            },
        ),
    ]
